# Generated by Django 4.1.7 on 2023-04-16 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
