# Generated by Django 4.1.7 on 2023-04-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_perfilfeed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='stats',
            new_name='status',
        ),
    ]
